version: "3.9"

services:
  postgres_db:
    container_name: postgres-database
    image: postgres:13
    networks:
      - gateway
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - PGDATA="/var/lib/postgresql/data/pgdata"
      - POSTGRES_PORT=5432
    restart: always

  car-dealership-application:
    container_name: car-dealership-application
    image: car-dealership-application-image
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    networks:
      - gateway
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
#      - eureka-naming-server
#      - credit-rating-8199
#      - credit-rating-8200



networks:
  gateway:
    driver: bridge
